blueprint:
  name: Paralelo Virtual V2.3 - rhsyamada
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_timeout:      
      name: Wait time
      description: Time to wait until off_action is called.
      default: 1000
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: milliseconds
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true

variables:
  delay_var: !input entrada_switchs

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input entrada_switchs  
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: "{{ delay_var }}"

mode: single
